export const BUSCA_ACTOR = "BUSCA_ACTOR"
export const BUSCA_PELICULAS ="BUSCA_PELICULAS";
export const OBTENER_GENEROS="OBTENER_GENEROS";
export const REINICIA_BUSCADOR="REINICIA_BUSCADOR";
export const IS_LISTADO="IS_LISTADO";
